# -*- coding: utf-8 -*-
"""
Colours and styling of the GUI

The look: one dark grey surface (window and plot
backgrounds the same grey, light grey text and ticks, no white plot areas,
no panel borders), magnetics in cyan-blue and electrics in red, panels
stacked with no gap on a shared x axis, and names such as "By-Ex (Zxy)".

`apply(app)` is called once on the `QApplication` before the main window is
built (in `__main__` and the smoke test). It sets:

* Qt: the Fusion style with a dark `QPalette`, so every widget (tables,
  lists, the YAML preview, the job log, the Process tab's forms) uses the
  same grey without stylesheets.
* pyqtgraph: the `background` and `foreground` config options, read by every
  `PlotWidget` created afterwards.
* matplotlib: the rcParams of the View EDIs canvas (figure and axes face,
  text, ticks, spines, grid, legend).

The tabs take their colours from this module: `colour(comp)` gives a
channel's colour by kind (`crust.gui.channels`; B_COLOUR for a magnetic
name such as hx or bx, E_COLOUR for an electric one such as ex or e1,
REMOTE_COLOUR for a remote's r_...), `label(comp)` its display name (Bx, By,
Ex, Ey, E1, rBx; `channels.label`) and `channel_order(names)` the stack order
(magnetics first, then electrics, each in name order). The module also
defines the Spectra tab's faint dashed Schumann and mains markers, the
Coherence tab's band colours, "All frequencies" curve and cursor, the
Process tab's status colours, site roles and summary text, and the Filter
Data tab's light grey raw trace (`RAW_COLOUR`, `raw_pen`).

@author: ben kay (ben@auscope.org.au)

:license: MIT
"""

from __future__ import annotations

import matplotlib
import pyqtgraph as pg
from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QPalette
from PySide6.QtWidgets import QProxyStyle, QStyle, QToolTip

from crust.gui.channels import kind, label, order as channel_order  # noqa: F401  (re-exported)

# ------------------------------------------------------------- the surface
WINDOW = "#2b2b2b"      # the window, buttons, tab bars
SURFACE = "#1f1f1f"     # text boxes, tables, lists and every plot area
TEXT = "#e6e6e6"        # widget text
FOREGROUND = "#c8c8c8"  # plot axes, ticks, tick labels and titles
DISABLED = "#7a7a7a"    # disabled text
HIGHLIGHT = "#3a6d99"   # selection: a muted blue
INDICATOR_EDGE = "#a0a0a0"  # the outline of a check box or radio button: see `_Style`
GRID_ALPHA = 0.3        # pyqtgraph grid opacity (a fraction of FOREGROUND)
MPL_GRID = "#4a4a4a"    # matplotlib grid lines

# ------------------------------------------------------------- the channels
# the stack order is `channel_order` (magnetics first, then electrics)
B_COLOUR = "#4fc3f7"       # magnetics: cyan-blue
E_COLOUR = "#ff5252"       # electrics: red
REMOTE_COLOUR = "#bdbdbd"  # the remote's coils: light grey

# ------------------------------------------- the Spectra tab's frequency marks
SCHUMANN_HZ = (7.83, 14.3, 20.8, 27.3, 33.8)
SCHUMANN_COLOUR = "#66bb6a"  # green
MAINS_HZ = 50.0              # and its harmonics up to Nyquist
MAINS_COLOUR = "#ffa726"     # orange
MARK_ALPHA = 110             # of 255: faint

# ------------------------------------------------------ the Coherence tab
BAND_COLOURS = ["#64b5f6", "#ffb74d", "#81c784", "#e57373", "#ba68c8"]  # one per BANDS_S row
ALL_FREQ_LABEL = "All frequencies"
ALL_FREQ_COLOUR = "#ffffff"
ALL_FREQ_WIDTH = 2.5
CURSOR_COLOUR = "#ffd54f"

# ------------------------------------------------------- the Process tab
# the Process tab's traffic light (the sync lamps and status line,
# the recommendation) and the site roles on the map and the window bar
OK_COLOUR = "#66bb6a"           # green: in sync, the recommended remote, the station
WARN_COLOUR = "#ffa726"         # amber: the remote covers part of the window; stack members
BAD_COLOUR = "#ef5350"          # red: no overlap, a span that could not be read, a failed job
IDLE_COLOUR = "#9e9e9e"         # grey: no remote yet or still reading; every other site
PAIR_REMOTE_COLOUR = "#42a5f5"  # blue: the remote's dot on the map and its bar
SUMMARY_COLOUR = "#4fc3f7"      # the pair summary's text: cyan-blue, as the magnetics
MARKER_EDGE = SURFACE           # the thin ring round a span bar
SITE_OUTLINE = "#000000"        # the dark ring round a map dot, so it reads on a basemap
SITE_LABEL_ALPHA = 170          # of 255: the SURFACE box behind a site name on the map, over imagery
REGION_ALPHA = 70               # of 255: the processing window's fill, in HIGHLIGHT

# ------------------------------------------------------ the Metadata tab
NOTICE_COLOUR = "#ffeb3b"       # yellow: "survey.yaml is generated by <script>: ..."

# --------------------------------------------------- the Filter Data tab
RAW_COLOUR = "#a6a6a6"          # light grey: the raw ("before") trace behind the filtered one


def colour(comp: str) -> str:
    """Return B_COLOUR for a magnetic channel, E_COLOUR for an electric one, REMOTE_COLOUR for a remote's."""
    if comp.startswith("r_"):
        return REMOTE_COLOUR
    return {"magnetic": B_COLOUR, "electric": E_COLOUR}.get(kind(comp), FOREGROUND)


def pen(comp: str, width: float = 1.0):
    """Return a pyqtgraph pen in the channel's colour."""
    return pg.mkPen(colour(comp), width=width)


def raw_pen(width: float = 1.0, dashed: bool = False):
    """Return the pen of the Filter Data tab's raw ("before") trace: light grey, dashed on the PSD panels."""
    return pg.mkPen(RAW_COLOUR, width=width, style=Qt.DashLine if dashed else Qt.SolidLine)


def mark_pen(hex_colour: str):
    """Return a faint dashed pen for a frequency mark."""
    c = QColor(hex_colour)
    c.setAlpha(MARK_ALPHA)
    return pg.mkPen(c, width=1, style=Qt.DashLine)


def _palette() -> QPalette:
    """Return the dark palette, with greyed disabled roles."""
    p = QPalette()
    roles = {
        QPalette.Window: WINDOW, QPalette.WindowText: TEXT,
        QPalette.Base: SURFACE, QPalette.AlternateBase: "#262626",
        QPalette.ToolTipBase: "#333333", QPalette.ToolTipText: TEXT,
        QPalette.PlaceholderText: "#8a8a8a",
        QPalette.Text: TEXT, QPalette.Button: WINDOW, QPalette.ButtonText: TEXT,
        QPalette.BrightText: "#ffffff",
        QPalette.Light: "#3c3c3c", QPalette.Midlight: "#333333", QPalette.Mid: "#262626",
        QPalette.Dark: "#1a1a1a", QPalette.Shadow: "#101010",
        QPalette.Highlight: HIGHLIGHT, QPalette.HighlightedText: "#ffffff",
        QPalette.Link: "#6fb3e0", QPalette.LinkVisited: "#b39ddb",
    }
    for role, value in roles.items():
        p.setColor(role, QColor(value))
    for role in (QPalette.Text, QPalette.WindowText, QPalette.ButtonText):
        p.setColor(QPalette.Disabled, role, QColor(DISABLED))
    p.setColor(QPalette.Disabled, QPalette.Highlight, QColor("#3a3a3a"))
    p.setColor(QPalette.Disabled, QPalette.HighlightedText, QColor(DISABLED))
    p.setColor(QPalette.Disabled, QPalette.Base, QColor("#242424"))
    return p


class _Style(QProxyStyle):
    """Fusion style with check box and radio button outlines drawn in INDICATOR_EDGE.

    Fusion takes an indicator's outline from the palette's Window colour,
    darkened, which leaves an unticked box invisible on this surface (in the
    View EDIs tree, the Filter Data forms and the Process tab's switches).
    Only the three indicator primitives are drawn with the changed palette,
    so frames and grids that also derive from Window stay borderless.
    """

    INDICATORS = (QStyle.PE_IndicatorCheckBox, QStyle.PE_IndicatorItemViewItemCheck,
                  QStyle.PE_IndicatorRadioButton)

    def drawPrimitive(self, element, option, painter, widget=None):
        """Draw indicator primitives with Window set to INDICATOR_EDGE; others unchanged."""
        if element not in self.INDICATORS:
            return super().drawPrimitive(element, option, painter, widget)
        kept = QPalette(option.palette)
        edged = QPalette(kept)
        edged.setColor(QPalette.Window, QColor(INDICATOR_EDGE))
        option.palette = edged
        try:
            super().drawPrimitive(element, option, painter, widget)
        finally:
            option.palette = kept


def apply(app) -> None:
    """Apply the dark Fusion style to `app` and the same colours to pyqtgraph and matplotlib."""
    app.setStyle(_Style("Fusion"))
    palette = _palette()
    app.setPalette(palette)
    QToolTip.setPalette(palette)
    pg.setConfigOptions(background=SURFACE, foreground=FOREGROUND)
    matplotlib.rcParams.update({
        "figure.facecolor": SURFACE, "figure.edgecolor": SURFACE,
        "axes.facecolor": SURFACE, "axes.edgecolor": FOREGROUND,
        "axes.labelcolor": TEXT, "axes.titlecolor": TEXT,
        "text.color": TEXT,
        "xtick.color": FOREGROUND, "ytick.color": FOREGROUND,
        "grid.color": MPL_GRID,
        "legend.facecolor": SURFACE, "legend.edgecolor": "#555555",
        "savefig.facecolor": SURFACE, "savefig.edgecolor": SURFACE,
    })
